### PR TITLE
MAD-12245 - added fixed magento 2.4.5-p1 files

### PR DESCRIPTION
**Pull request by ppf**

### CODE REVIEW

**Comment by ChrisOrlando** [comment]
@ppf what is different about these files? you'll probably want to pull in latest changes and redo this PR since solving branch conflicts w/ git-lfs might be annoying.

**Comment by ChrisOrlando** [comment]
@ppf also, i have a tarball that i'm using for nexkit already that should work the same as existing ones if you'd like that. it would alleviate the need to make then nxcli changes you're working on

**Comment by ppf** [comment]
@ChrisOrlando I solved the conflicts already. The files were removed from the master by Frank yesterday so it was pretty easy. I have a tarball directly from there: https://github.com/magento/magento2/releases 
so should be ok, but if you have any additional modifications in the files which helps with the installation please let me know or send the files.

**Comment by ChrisOrlando** [comment]
@ppf 
if you use this one you won't need any code changes and we can share the new ones going forward between nxcli and nexkit which should reduce duplicate work

http://pubfiles.nexcess.net/magento/ce-packages/magento2-2.4.5-p1.tar.gz

i have a script to make a tarball that matches the way the old ones were structured too. i'm not saying we have to do this, but offering it as an option.

**Comment by ppf** [comment]
@ChrisOrlando you're right. I will check this tar, if it will work without any nxcli changes I will close the nxcli PR.

**Review by ChrisOrlando — APPROVED** [review]

**Comment by adrian-enspired** [comment]
This is **blocked** on MAD-12277, 12278, 12279

**Comment by ppf** [comment]
@adrian-enspired @ChrisOrlando 
needed to update PHP version for the Magento 2.4.5 to 8.1
https://github.com/nocworx/core/pull/8406 - it needs to be deployed before or at the same time as this app-sources PR

**Pull request merged**
